<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cir</string>
	</array>
	<key>name</key>
	<string>Circuitry</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#custom_component</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#connection</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#component_declaration</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.circuitry</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.circuitry</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *| +)((#).*)</string>
		</dict>
		<key>component_declaration</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.circuitry</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.component.circuitry</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[([A-Za-z_0-9]+|\[(?:[A-Za-z_0-9]+,?\s*)+\])\s+[A-Za-z_0-9]+\]</string>
		</dict>
		<key>connection</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.circuitry</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.circuitry</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>language.parameter.circuitry</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.circuitry</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.language.circuitry</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.other.circuitry</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>language.parameter.circuitry</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:(self)|(\w+))\[(\w+|(?:\[(?:\w+,?\s*)+\]))\] (-&gt;) (?:(self)|(\w+))\[(\w+|(?:\[(?:\w+,?\s*)+\]))\]</string>
		</dict>
		<key>custom_component</key>
		<dict>
			<key>begin</key>
			<string>(&lt;)([A-Za-z_0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.circuitry</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.component.circuitry</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.circuitry</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.circuitry</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+</string>
					<key>contentName</key>
					<string>meta.function.inline.parameters.circuitry</string>
					<key>end</key>
					<string>(?=&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.circuitry</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.parameters.circuitry</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b([a-zA-Z_][a-zA-Z_0-9]*)\s*(?:(,)|(?=[\n&gt;\]]))</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.circuitry</string>
	<key>uuid</key>
	<string>88278c9f-17f6-47f2-8eec-673c66f756c3</string>
</dict>
</plist>
